"""
Dev Agent — core logic.

Receives the QA Agent's failing test case, calls the LLM to generate a
minimal code fix, posts the fix as a comment on the GitHub Issue, then
notifies the team via Slack and email.

Entry points:
  handle()  — called on test_case_generated events
"""

import base64
import logging

import httpx
import redis.asyncio as redis

from agents.dev import prompts
from core.config import get_email_config, get_github_config, get_slack_config
from core.events import publish
from core.llm import complete
from core.models import CrashReport, QAResult
from core.state import write_status
from integrations import email, github, slack

logger = logging.getLogger(__name__)

# Maximum characters to read per source file passed to the LLM.
_MAX_FILE_CHARS = 4_000


async def handle(
    qa_result: QAResult,
    crash_report: CrashReport,
    redis_client: redis.Redis,
) -> None:
    """
    Generate a fix suggestion for the failing test and notify the team.

    Steps:
      1. Fetch relevant source files from GitHub (no clone).
      2. Call the LLM to suggest a minimal code fix.
      3. Post the fix as a comment on the GitHub Issue.
      4. Notify via Slack and email with a link to the issue.
      5. Publish the fix_suggested event.

    Args:
        qa_result:    QAResult from the QA Agent (contains the failing test case).
        crash_report: CrashReport from the Crash Handler Agent.
        redis_client: Async Redis client.
    """
    gh_config = get_github_config()
    incident_id = crash_report.incident_id

    logger.info("dev agent started", extra={"incident_id": incident_id})

    # Step 1 — Fetch source files from GitHub API.
    source_files = await _fetch_source_files(
        repo=gh_config.target_repo,
        paths=qa_result.relevant_files,
    )
    logger.debug(
        "source files fetched",
        extra={"incident_id": incident_id, "files": list(source_files.keys())},
    )

    # Step 2 — LLM generates the fix.
    prompt = prompts.build(
        error_type=crash_report.error_type,
        error_message=crash_report.error_message,
        summary=crash_report.summary,
        test_file_path=qa_result.test_case.file_path,
        test_name=qa_result.test_case.test_name,
        test_content=qa_result.test_case.content,
        source_files=source_files,
    )

    logger.info("dev agent calling llm for fix suggestion", extra={"incident_id": incident_id})
    fix_response = await complete(agent="dev", prompt=prompt)
    logger.debug(
        "llm fix response received",
        extra={"incident_id": incident_id, "response_length": len(fix_response)},
    )

    # Step 3 — Post the fix as a GitHub Issue comment.
    issue_comment = (
        f"**Suggested fix** for `{crash_report.error_type}: {crash_report.error_message}`\n\n"
        f"{fix_response}\n\n"
        f"---\n"
        f"*Generated by Helix for incident `{incident_id}`. "
        f"Please review and apply manually.*"
    )
    logger.debug(
        "posting fix comment to github issue",
        extra={"incident_id": incident_id, "issue_number": qa_result.ticket_id},
    )
    await github.add_issue_comment(
        repo=gh_config.target_repo,
        issue_number=qa_result.ticket_id,
        comment=issue_comment,
    )
    logger.info(
        "fix comment posted to github issue",
        extra={"incident_id": incident_id, "issue_number": qa_result.ticket_id},
    )

    # Step 4 — Notify via Slack and email.
    slack_config = get_slack_config()
    email_config = get_email_config()

    slack_text = (
        f":wrench: *Helix suggested a fix* for incident `{incident_id}`\n"
        f"*Error:* `{crash_report.error_type}: {crash_report.error_message}`\n"
        f"*Component:* {crash_report.affected_component}\n"
        f"*Review the fix:* {qa_result.ticket_url}"
    )
    await slack.post_message(
        text=slack_text,
        channel=slack_config.approval_channel,
        token=slack_config.token,
    )

    await email.send_fix_suggested(
        incident_id=incident_id,
        error_type=crash_report.error_type,
        error_message=crash_report.error_message,
        issue_url=qa_result.ticket_url,
        from_addr=email_config.from_addr,
        to_addr=email_config.to_addrs,
        sendgrid_api_key=email_config.sendgrid_api_key,
        smtp_host=email_config.smtp_host,
        smtp_port=email_config.smtp_port,
        smtp_user=email_config.smtp_user,
        smtp_password=email_config.smtp_password,
    )
    logger.info(
        "slack and email notifications sent",
        extra={"incident_id": incident_id},
    )

    # Step 5 — Update Redis status and publish event.
    await write_status(redis_client, incident_id, "fix_suggested")
    await publish(
        redis_client,
        "fix_suggested",
        incident_id,
        {
            "incident_id": incident_id,
            "issue_url": qa_result.ticket_url,
            "ticket_id": qa_result.ticket_id,
        },
    )
    logger.info("dev agent complete", extra={"incident_id": incident_id})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _fetch_source_files(repo: str, paths: list[str]) -> dict[str, str]:
    """
    Fetch the content of source files from the GitHub contents API.

    Args:
        repo:  Repository in "owner/name" format.
        paths: Relative file paths to fetch (from qa_result.relevant_files).

    Returns:
        Mapping of relative path → file content (truncated if large).
        Files that cannot be fetched are silently skipped.
    """
    from integrations.github import _api_headers, _GITHUB_API

    result: dict[str, str] = {}
    async with httpx.AsyncClient() as client:
        for path in paths:
            url = f"{_GITHUB_API}/repos/{repo}/contents/{path}"
            try:
                response = await client.get(url, headers=_api_headers())
                response.raise_for_status()
                data = response.json()
                content = base64.b64decode(data["content"]).decode("utf-8", errors="replace")
                if len(content) > _MAX_FILE_CHARS:
                    content = content[:_MAX_FILE_CHARS] + "\n... [truncated]"
                result[path] = content
                logger.debug("fetched source file", extra={"path": path})
            except Exception as exc:
                logger.warning(
                    "could not fetch source file",
                    extra={"path": path, "error": str(exc)},
                )
    return result
