"""
LLM prompts for the Dev Agent.

Two prompts are used in sequence:

  build_suggestion() — sent to the Anthropic API to generate a human-readable
      fix suggestion that is posted as a GitHub Issue comment.

  build_tdd() — sent to the claude-code CLI (running inside the cloned repo)
      to implement the fix using a TDD loop. It receives the suggestion from
      the first call as additional context so the CLI has a concrete starting
      point.

The TDD prompt uses a sentinel protocol: the CLI must output either
"TESTS_PASSED" or "TESTS_FAILED" followed by a short explanation so the
agent can decide whether to commit the fix or retry.
"""


def build_suggestion(
    error_type: str,
    error_message: str,
    summary: str,
    test_file_path: str,
    test_name: str,
    test_content: str,
    source_files: dict[str, str],
) -> str:
    """
    Build the fix-suggestion prompt for the Anthropic API call.

    The response is posted as a GitHub Issue comment for the engineering team
    to review. It is also passed to build_tdd() as context for the
    implementation step.

    Args:
        error_type:     Exception class, e.g. "AttributeError".
        error_message:  Exception message.
        summary:        Plain-English crash summary from the Crash Handler.
        test_file_path: Path to the failing test file.
        test_name:      Failing test function name.
        test_content:   Full content of the failing test.
        source_files:   Mapping of file path → content for relevant source files.

    Returns:
        Prompt string ready to send to the Anthropic API.
    """
    source_section = ""
    if source_files:
        source_section = "\n## Relevant Source Files\n"
        for path, content in source_files.items():
            source_section += f"\n### `{path}`\n```python\n{content}\n```\n"
    else:
        source_section = "\n## Relevant Source Files\n_(No source files available.)_\n"

    return f"""\
You are a senior software engineer reviewing a production bug.

## Bug Summary
- **Error type:** {error_type}
- **Error message:** {error_message}
- **Summary:** {summary}

## Failing Test
The following test was written to reproduce this bug. It currently fails.

**File:** `{test_file_path}`
**Test:** `{test_name}`

```python
{test_content}
```
{source_section}
## Your Task

Write the minimal code change that makes the failing test pass without breaking other functionality.

The test asserts the CORRECT behaviour — it does not assert that an exception is raised.
Your fix must make the function return the expected value instead of crashing.

Your response must:
1. Identify the root cause in one sentence.
2. Show the exact code change using clearly labelled BEFORE and AFTER blocks.
   - The AFTER block MUST include the defensive guard or fix — it must not be
     identical to the BEFORE block.
   - Example of a correct guard for a None-dereference bug:
     BEFORE: `return f"Hello, {{user.get('name')}}!"`
     AFTER:  `if user is None: return None` (then the original return)
3. Explain why this change makes the test pass in 2–3 sentences.

Be concise. Do not refactor unrelated code. Do not add new dependencies.
"""


def build_tdd(
    incident_id: str,
    error_type: str,
    error_message: str,
    summary: str,
    test_file_path: str,
    test_name: str,
    iteration: int,
    prior_attempts: list[str],
    fix_suggestion: str = "",
    language: str = "python",
) -> str:
    """
    Build the implementation prompt for the claude-code CLI (TDD loop).

    This prompt is passed to `claude -p "..."` inside the cloned repo. The
    claude-code CLI runs the failing test, applies a fix, and runs the full
    suite. It must output a TESTS_PASSED or TESTS_FAILED sentinel so the
    agent can decide whether to commit or retry.

    Args:
        incident_id:    Helix incident ID (for traceability in commits/logs).
        error_type:     Exception class, e.g. "KeyError".
        error_message:  Exception message.
        summary:        Plain-English crash summary from the Crash Handler.
        test_file_path: Relative path to the failing test already written into
                        the repo, e.g. "tests/test_checkout.py".
        test_name:      Test function name.
        iteration:      Current attempt number (1-indexed).
        prior_attempts: Summaries from previous failed attempts, oldest first.
        fix_suggestion: The fix suggestion generated by build_suggestion() and
                        already posted to the GitHub Issue. Used as a starting
                        point — do not blindly copy it.
        language:       Application language, e.g. "python", "javascript", "go".

    Returns:
        Prompt string ready to pass to `claude -p "..."`.
    """
    prior_section = ""
    if prior_attempts:
        prior_section = "\n## Previous Attempts (do not repeat these approaches)\n"
        for i, attempt in enumerate(prior_attempts, start=1):
            prior_section += f"\n### Attempt {i}\n{attempt}\n"

    suggestion_section = ""
    if fix_suggestion:
        suggestion_section = (
            f"\n## Suggested Fix (hint only — may be incomplete or wrong)\n"
            f"This was posted to the GitHub Issue as a starting point. "
            f"Do NOT apply it blindly. Run the test first, read the actual error, "
            f"then decide whether the suggestion is correct:\n\n"
            f"{fix_suggestion}\n"
        )

    hint_one, hint_all = _test_commands(language, test_file_path, test_name)

    return f"""\
The repository is already cloned in the current working directory. Do NOT ask for files. Do NOT write a plan. Start immediately by running pytest on the test file. Take action now.

You are fixing a production bug for incident {incident_id} (attempt {iteration}/3).

## Bug Context
- Language:      {language}
- Error type:    {error_type}
- Error message: {error_message}
- Summary:       {summary}

## Failing Test
A test that reproduces this bug has already been written to:
  {test_file_path}

Test function: {test_name}
{prior_section}{suggestion_section}
## Your Task
Follow these steps exactly:

1. Discover the environment and install any missing dependencies.

   a. Read README.md (if it exists) for setup instructions.

   b. Identify the build system and test runner by checking for these files
      in order of priority:
        build.gradle / build.gradle.kts  → Gradle
        pom.xml                          → Maven
        package.json                     → npm / yarn / pnpm
        go.mod                           → go test
        Cargo.toml                       → cargo test
        pyproject.toml / setup.py /
        requirements.txt                 → pytest / unittest
        Makefile                         → check targets for "test"

   c. If the required build tool is not installed, install it now without
      asking. Use the appropriate method for the OS:
        - Java/Kotlin (Gradle or Maven): install via SDKMAN if available
          (`sdk install java`, `sdk install gradle`, `sdk install maven`),
          otherwise use the system package manager (apt-get / brew).
        - Node.js: install via nvm or system package manager.
        - Go / Rust / Python: use the system package manager or official
          installer scripts.

   d. Install project dependencies:
        Gradle  → ./gradlew dependencies  (use the wrapper if present)
        Maven   → mvn dependency:resolve -q
        npm     → npm install
        yarn    → yarn install
        pnpm    → pnpm install
        Go      → go mod download
        Rust    → cargo fetch
        Python  → pip install -r requirements.txt  (or pip install -e .[dev]
                  if pyproject.toml is present)

   Hint (based on the reported language "{language}"):
     single test : {hint_one}
     full suite  : {hint_all}
   These are hints only — if the actual build file points to a different
   tool (e.g. Gradle instead of Maven), use the correct tool.

2. Run the failing test to confirm it currently fails using the test runner
   you identified in step 1.

3. Read the relevant source files to understand the bug.

4. Write the minimal code change that makes the test pass.
   - The test asserts correct behaviour (e.g. a return value) — not that an
     exception is raised. Your fix must make the function return the expected
     value rather than crash.
   - Fix only the bug — do not refactor, rename, or clean up unrelated code.
   - Do not modify the test file.
   - Do not add new dependencies.

5. Run the full test suite to check for regressions.

6. Based on the results, output ONE of the following sentinel lines,
   followed by a short explanation:

   If all tests pass:
      TESTS_PASSED
      <one paragraph: what you changed and why>

   If tests still fail:
      TESTS_FAILED
      <one paragraph: what you tried and why it did not work>

Do not output anything else after the sentinel line and explanation.
"""


def build_tdd_short(
    test_file_path: str,
    test_name: str,
    summary: str,
    language: str = "python",
) -> str:
    """
    Compact TDD prompt for local/small models (goose + ollama).

    Skips the multi-language environment-discovery matrix from build_tdd() —
    local models tend to treat that as an invitation to plan rather than act.
    """
    run_one, _ = _test_commands(language, test_file_path, test_name)

    return f"""The repository is already cloned in the current working directory.
You have the shell tool. Use it immediately. Do not write explanations. Do not describe what you will do. Just run commands.

Step 1: Install dependencies.
Run: uv run --no-project pip install -e . -q 2>/dev/null || true

Step 2: Run the test to see the failure.
Run: {run_one} 2>&1

Step 3: Read the traceback. Find the source file and line number that contains the bug. Do not touch the test file. Fix the source file using the shell tool with a command like:
uv run --no-project python -c "
with open('path/to/source.py') as f:
    code = f.read()
code = code.replace('broken line', 'fixed line')
with open('path/to/source.py', 'w') as f:
    f.write(code)
"

Step 4: Run the test again.
Run: {run_one} 2>&1

Step 5: Output exactly one of these two lines and nothing else:
TESTS_PASSED
TESTS_FAILED

Bug description: {summary}
Language: {language}"""


def _test_commands(language: str, test_file_path: str, test_name: str) -> tuple[str, str]:
    """
    Return hint commands (run_one, run_all) for the given language.

    These are passed to build_tdd() as hints only. The TDD prompt instructs
    the claude-code CLI to inspect the actual repo build files and override
    these hints when the real build system differs (e.g. Gradle instead of
    Maven for a Java repo).

    Args:
        language:       Application language, e.g. "python", "javascript".
        test_file_path: Relative path to the test file.
        test_name:      Test function/method name.

    Returns:
        A (run_one, run_all) tuple of shell command strings.
    """
    lang = language.lower()

    if lang in ("javascript", "typescript"):
        return (
            f'npx jest --testPathPattern "{test_file_path}" --testNamePattern "{test_name}" --verbose',
            "npx jest",
        )
    if lang == "ruby":
        return (
            f'bundle exec rspec "{test_file_path}" --example "{test_name}"',
            "bundle exec rspec",
        )
    if lang in ("java", "kotlin"):
        return (
            f'mvn test -Dtest="{test_name}" -q',
            "mvn test -q",
        )
    if lang == "go":
        return (
            f'go test ./... -run "^{test_name}$" -v',
            "go test ./...",
        )
    # Python (default)
    return (
        f"pytest {test_file_path}::{test_name} -v",
        "pytest",
    )
