"""
LLM prompts for the Dev Agent.

Two prompts are used in sequence:

  build_suggestion() — sent to the Anthropic API to generate a human-readable
      fix suggestion that is posted as a GitHub Issue comment.

  build_tdd() — sent to the claude-code CLI (running inside the cloned repo)
      to implement the fix using a TDD loop. It receives the suggestion from
      the first call as additional context so the CLI has a concrete starting
      point.

The TDD prompt uses a sentinel protocol: the CLI must output either
"TESTS_PASSED" or "TESTS_FAILED" followed by a short explanation so the
agent can decide whether to commit the fix or retry.
"""


def build_suggestion(
    error_type: str,
    error_message: str,
    summary: str,
    test_file_path: str,
    test_name: str,
    test_content: str,
    source_files: dict[str, str],
) -> str:
    """
    Build the fix-suggestion prompt for the Anthropic API call.

    The response is posted as a GitHub Issue comment for the engineering team
    to review. It is also passed to build_tdd() as context for the
    implementation step.

    Args:
        error_type:     Exception class, e.g. "AttributeError".
        error_message:  Exception message.
        summary:        Plain-English crash summary from the Crash Handler.
        test_file_path: Path to the failing test file.
        test_name:      Failing test function name.
        test_content:   Full content of the failing test.
        source_files:   Mapping of file path → content for relevant source files.

    Returns:
        Prompt string ready to send to the Anthropic API.
    """
    source_section = ""
    if source_files:
        source_section = "\n## Relevant Source Files\n"
        for path, content in source_files.items():
            source_section += f"\n### `{path}`\n```python\n{content}\n```\n"
    else:
        source_section = "\n## Relevant Source Files\n_(No source files available.)_\n"

    return f"""\
You are a senior software engineer reviewing a production bug.

## Bug Summary
- **Error type:** {error_type}
- **Error message:** {error_message}
- **Summary:** {summary}

## Failing Test
The following test was written to reproduce this bug. It currently fails.

**File:** `{test_file_path}`
**Test:** `{test_name}`

```python
{test_content}
```
{source_section}
## Your Task

Write the minimal code change that will make the failing test pass without breaking other functionality.

Your response must:
1. Identify the root cause in one sentence.
2. Show the exact code change using a diff or clearly labelled before/after blocks.
3. Explain why this change fixes the bug in 2–3 sentences.

Be concise. Do not refactor unrelated code. Do not add new dependencies.
"""


def build_tdd(
    incident_id: str,
    error_type: str,
    error_message: str,
    summary: str,
    test_file_path: str,
    test_name: str,
    iteration: int,
    prior_attempts: list[str],
    fix_suggestion: str = "",
) -> str:
    """
    Build the implementation prompt for the claude-code CLI (TDD loop).

    This prompt is passed to `claude -p "..."` inside the cloned repo. The
    claude-code CLI runs the failing test, applies a fix, and runs the full
    suite. It must output a TESTS_PASSED or TESTS_FAILED sentinel so the
    agent can decide whether to commit or retry.

    Args:
        incident_id:    Helix incident ID (for traceability in commits/logs).
        error_type:     Exception class, e.g. "KeyError".
        error_message:  Exception message.
        summary:        Plain-English crash summary from the Crash Handler.
        test_file_path: Relative path to the failing test already written into
                        the repo, e.g. "tests/test_checkout.py".
        test_name:      Test function name.
        iteration:      Current attempt number (1-indexed).
        prior_attempts: Summaries from previous failed attempts, oldest first.
        fix_suggestion: The fix suggestion generated by build_suggestion() and
                        already posted to the GitHub Issue. Used as a starting
                        point — do not blindly copy it.

    Returns:
        Prompt string ready to pass to `claude -p "..."`.
    """
    prior_section = ""
    if prior_attempts:
        prior_section = "\n## Previous Attempts (do not repeat these approaches)\n"
        for i, attempt in enumerate(prior_attempts, start=1):
            prior_section += f"\n### Attempt {i}\n{attempt}\n"

    suggestion_section = ""
    if fix_suggestion:
        suggestion_section = (
            f"\n## Suggested Fix (already posted to GitHub Issue)\n"
            f"Use this as a starting point, but verify it against the actual code:\n\n"
            f"{fix_suggestion}\n"
        )

    return f"""\
You are fixing a production bug for incident {incident_id} (attempt {iteration}/3).

## Bug Context
- Error type:    {error_type}
- Error message: {error_message}
- Summary:       {summary}

## Failing Test
A test that reproduces this bug has already been written to:
  {test_file_path}

Test function: {test_name}
{prior_section}{suggestion_section}
## Your Task
Follow these steps exactly:

1. Run the failing test to confirm it currently fails:
      pytest {test_file_path}::{test_name} -v

2. Read the relevant source files to understand the bug.

3. Write the minimal code change that makes the test pass.
   - Fix only the bug — do not refactor, rename, or clean up unrelated code.
   - Do not modify the test file.
   - Do not add new dependencies.

4. Run the full test suite to check for regressions:
      pytest

5. Based on the results, output ONE of the following sentinel lines,
   followed by a short explanation:

   If all tests pass:
      TESTS_PASSED
      <one paragraph: what you changed and why>

   If tests still fail:
      TESTS_FAILED
      <one paragraph: what you tried and why it did not work>

Do not output anything else after the sentinel line and explanation.
"""
