/* Data / fixtures — shared across screens */

const AGENTS = {
  handler: { id: 'handler', name: 'Crash Handler', short: 'handler', color: 'var(--handler)', symbol: '◆' },
  qa:      { id: 'qa',      name: 'QA Agent',      short: 'qa',      color: 'var(--qa)',      symbol: '▲' },
  dev:     { id: 'dev',     name: 'Dev Agent',     short: 'dev',     color: 'var(--dev)',     symbol: '●' },
  human:   { id: 'human',   name: 'Human',         short: 'human',   color: 'var(--human)',   symbol: '◐' },
};

const STATUSES = {
  crash:     { label: 'Crash',       color: 'var(--crash)' },
  analysing: { label: 'Analysing',   color: 'var(--warn)'  },
  testing:   { label: 'Test Gen',    color: 'var(--qa)'    },
  fixing:    { label: 'Fixing',      color: 'var(--dev)'   },
  pr:        { label: 'PR Created',  color: 'var(--dev)'   },
  approval:  { label: 'Approval',    color: 'var(--human)' },
  merged:    { label: 'Merged',      color: 'var(--ok)'    },
  duplicate: { label: 'Duplicate',   color: 'var(--ink-3)' },
  failed:    { label: 'Failed',      color: 'var(--crash)' },
};

const INCIDENTS = [
  {
    id: '7e5ebf67-8315-47fb-a49e-5552975b98d3',
    short: '7e5ebf67',
    error: 'AttributeError',
    message: "'NoneType' object has no attribute 'get'",
    component: 'user_greeting',
    severity: 'high',
    status: 'approval',
    createdAt: '22 Apr · 19:01',
    createdAtLong: '22 Apr 2026, 19:01:21',
    endpoint: 'greet_user()',
    language: 'python 3.12.13',
    source: 'rollbar',
    pr: '#76',
    tddIter: '1/3',
    occurrences: 14,
    users: 9,
    progress: 0.8,
    summary: "The greet_user() function receives a None value instead of a user object and attempts to call .get() on it, causing an AttributeError. Users attempting to trigger the greeting feature will encounter a crash rather than a greeting message.",
    currentStage: 3,
  },
  {
    id: 'f349b2be-1aa5-4210-a7e9-9a67cb12d014',
    short: 'f349b2be',
    error: 'KeyError',
    message: "'amount'",
    component: 'payments',
    severity: 'high',
    status: 'duplicate',
    createdAt: '22 Apr · 18:56',
    source: 'sentry',
    occurrences: 3,
    users: 2,
    duplicateOf: '8908bfba',
  },
  {
    id: 'e60c9f47-2c9b-4c1a-a4bb-41a09b6f1291',
    short: 'e60c9f47',
    error: 'KeyError',
    message: "'amount'",
    component: 'payments',
    severity: 'high',
    status: 'duplicate',
    createdAt: '22 Apr · 18:56',
    source: 'sentry',
    occurrences: 1,
    users: 1,
    duplicateOf: '8908bfba',
  },
  {
    id: '8908bfba-9047-4f12-bd14-3b7d1a8d82a1',
    short: '8908bfba',
    error: 'KeyError',
    message: "'amount'",
    component: 'payments',
    severity: 'high',
    status: 'pr',
    createdAt: '20 Apr · 21:41',
    source: 'sentry',
    pr: '#74',
    occurrences: 28,
    users: 18,
    progress: 0.6,
  },
  {
    id: '67715fdc-4411-4a0d-84e8-1b6d1a8de09a',
    short: '67715fdc',
    error: 'IndexError',
    message: 'list index out of range',
    component: 'error',
    severity: 'high',
    status: 'pr',
    createdAt: '20 Apr · 21:09',
    source: 'rollbar',
    pr: '#72',
    occurrences: 6,
    users: 4,
    progress: 0.6,
  },
  {
    id: '1c44cbaa-ee21-4c2f-90aa-0f2e41a2df10',
    short: '1c44cbaa',
    error: 'TypeError',
    message: "unsupported operand type(s) for +: 'int' and 'NoneType'",
    component: 'analytics',
    severity: 'medium',
    status: 'merged',
    createdAt: '20 Apr · 14:03',
    source: 'rollbar',
    pr: '#71',
    occurrences: 22,
    users: 11,
    progress: 1,
  },
  {
    id: '9a2101bb-6bc7-4d91-b4c1-5f7ba1dd0001',
    short: '9a2101bb',
    error: 'ValueError',
    message: 'invalid literal for int() with base 10: \'\'',
    component: 'forms.signup',
    severity: 'low',
    status: 'failed',
    createdAt: '19 Apr · 11:22',
    source: 'sentry',
    occurrences: 4,
    users: 3,
    note: 'TDD budget exhausted — escalated',
  },
  {
    id: 'bc0e55cd-ea83-4a21-a13a-6f17c2a0ac99',
    short: 'bc0e55cd',
    error: 'TimeoutError',
    message: 'read timed out after 30s',
    component: 'search.index',
    severity: 'medium',
    status: 'analysing',
    createdAt: '19 Apr · 09:41',
    source: 'rollbar',
    occurrences: 2,
    users: 2,
    progress: 0.15,
  },
];

// Tool calls for the focused incident
const TOOL_CALLS = [
  { agent:'handler', tool:'LLM',     action:'Generate',        payload:'crash_handler',   t:'19:01:21', ok:true },
  { agent:'qa',      tool:'GitHub',  action:'Search issues',   payload:'no match',        t:'19:01:21', ok:true },
  { agent:'qa',      tool:'GitHub',  action:'Create issue',    payload:'#75',             t:'19:01:22', ok:true },
  { agent:'qa',      tool:'Git',     action:'Clone repo',      payload:'88hours/helix-test', t:'19:01:23', ok:true },
  { agent:'qa',      tool:'LLM',     action:'Generate',        payload:'ATTEMPT 1',       t:'19:01:26', ok:true },
  { agent:'qa',      tool:'GitHub',  action:'Add comment',     payload:'#75 test case',   t:'19:01:27', ok:true },
  { agent:'dev',     tool:'GitHub',  action:'Fetch files',     payload:'0 files',         t:'19:01:27', ok:true },
  { agent:'dev',     tool:'LLM',     action:'Generate',        payload:'fix suggestion',  t:'19:01:58', ok:true },
  { agent:'dev',     tool:'GitHub',  action:'Add comment',     payload:'#75 fix suggestion', t:'19:01:59', ok:true },
  { agent:'dev',     tool:'Git',     action:'Clone repo',      payload:'88hours/helix-test', t:'19:02:00', ok:true },
  { agent:'dev',     tool:'Claude',  action:'TDD iterate',     payload:'iteration 1/3',   t:'19:02:48', ok:true },
  { agent:'dev',     tool:'GitHub',  action:'Commit & push',   payload:'helix/fix/7e5ebf67-1', t:'19:02:47', ok:true },
  { agent:'dev',     tool:'GitHub',  action:'Create PR',       payload:'#76',             t:'19:02:49', ok:true },
];

// Activity log for the focused incident
const ACTIVITY_LOG = [
  { t:'19:01:21', agent:'handler', kind:'info',  text:'Incident received from Rollbar' },
  { t:'19:01:21', agent:'handler', kind:'info',  text:'Fingerprint: AttributeError:user_greeting:greet_user' },
  { t:'19:01:21', agent:'handler', kind:'info',  text:'No duplicates in last 7d — new incident' },
  { t:'19:01:21', agent:'handler', kind:'llm',   text:'Analysing crash context and stack trace…' },
  { t:'19:01:21', agent:'handler', kind:'done',  text:'Handoff to QA Agent' },
  { t:'19:01:22', agent:'qa',      kind:'tool',  text:'github.search_issues(repo=helix-test) → 0 matches' },
  { t:'19:01:22', agent:'qa',      kind:'tool',  text:'github.create_issue(#75) "AttributeError in greet_user"' },
  { t:'19:01:23', agent:'qa',      kind:'tool',  text:'git.clone 88hours/helix-test @main' },
  { t:'19:01:23', agent:'qa',      kind:'info',  text:'Read 6 relevant source file(s)' },
  { t:'19:01:23', agent:'qa',      kind:'llm',   text:'Generating test case (attempt 1)…' },
  { t:'19:01:27', agent:'qa',      kind:'info',  text:'Test case written: tests/test_user_greeting.py::test_greet_user_returns_greeting_for_valid_username' },
  { t:'19:01:27', agent:'qa',      kind:'done',  text:'test_case_generated' },
  { t:'19:01:27', agent:'qa',      kind:'done',  text:'Test case complete — handing off to Dev Agent' },
  { t:'19:01:27', agent:'dev',     kind:'info',  text:'Dev Agent started — fetching source files…' },
  { t:'19:01:27', agent:'dev',     kind:'info',  text:'Fetched 0 source file(s) — generating fix suggestion…' },
  { t:'19:01:59', agent:'dev',     kind:'info',  text:'Fix suggestion posted to GitHub issue — starting TDD loop…' },
  { t:'19:02:00', agent:'dev',     kind:'tool',  text:'git.clone 88hours/helix-test @main' },
  { t:'19:02:08', agent:'dev',     kind:'llm',   text:'TDD iteration 1/3 — running Claude Code…' },
  { t:'19:02:48', agent:'dev',     kind:'done',  text:'Tests passed on iteration 1 — PR #76 created' },
  { t:'19:02:49', agent:'dev',     kind:'done',  text:'pr_created' },
  { t:'19:02:49', agent:'dev',     kind:'done',  text:'Fix complete — awaiting human approval for PR #76' },
];

// Synthetic PR diff for the focused incident
const PR_DIFF = {
  pr: '#76',
  title: 'fix(user_greeting): guard against None user in greet_user()',
  branch: 'helix/fix/7e5ebf67-1',
  base: 'main',
  files: 2,
  additions: 18,
  deletions: 4,
  hunks: [
    { file: 'src/user_greeting.py', lines: [
      { k:'ctx', n:'12', t:'def greet_user(user):' },
      { k:'del', n:'13', t:'    name = user.get("name", "friend")' },
      { k:'del', n:'14', t:'    return f"Hello, {name}!"' },
      { k:'add', n:'13', t:'    if user is None:' },
      { k:'add', n:'14', t:'        return "Hello, friend!"' },
      { k:'add', n:'15', t:'    name = user.get("name", "friend")' },
      { k:'add', n:'16', t:'    return f"Hello, {name}!"' },
    ]},
    { file: 'tests/test_user_greeting.py', lines: [
      { k:'ctx', n:'1',  t:'from app.user_greeting import greet_user' },
      { k:'add', n:'2',  t:'' },
      { k:'add', n:'3',  t:'def test_greet_user_returns_greeting_for_valid_username():' },
      { k:'add', n:'4',  t:'    assert greet_user({"name": "Ada"}) == "Hello, Ada!"' },
      { k:'add', n:'5',  t:'' },
      { k:'add', n:'6',  t:'def test_greet_user_handles_none():' },
      { k:'add', n:'7',  t:'    assert greet_user(None) == "Hello, friend!"' },
    ]},
  ],
};

const STACK_TRACE = [
  { file: 'app/main.py', line: 42, fn: 'handle_request' },
  { file: 'app/routes/greeting.py', line: 17, fn: 'greeting_endpoint' },
  { file: 'app/user_greeting.py', line: 13, fn: 'greet_user', highlight: true },
];

// Expose
Object.assign(window, { AGENTS, STATUSES, INCIDENTS, TOOL_CALLS, ACTIVITY_LOG, PR_DIFF, STACK_TRACE });
