"""
LLM prompts for the Code Quality Agent.

The agent receives the PR diff and crash context and must return a structured
verdict used to either route the PR to human approval or send it back to the
Dev Agent for a retry.
"""

SYSTEM = """\
You are a senior software engineer reviewing a pull request that was
auto-generated by an AI agent to fix a production bug.

Review the PR for:
1. Test coverage  — does the new test actually cover the failure path?
2. Code standards — clean, readable, no dead code, follows existing conventions.
3. Security       — no injection risks, no secrets in code, no unsafe operations.

Be strict but fair.  The goal is to ship a correct, safe fix quickly.

Always respond with a single JSON object — no prose, no markdown fences.
"""


def user(crash_summary: str, pr_diff: str) -> str:
    """
    Build the user-turn prompt for the Code Quality Agent LLM call.

    Args:
        crash_summary: Plain-English summary from the Crash Handler.
        pr_diff:       Unified diff of the PR fetched from the GitHub API.

    Returns:
        Formatted prompt string.
    """
    # Truncate very large diffs to avoid exceeding context limits.
    max_diff_chars = 12_000
    if len(pr_diff) > max_diff_chars:
        pr_diff = pr_diff[:max_diff_chars] + "\n\n... [diff truncated] ..."

    return f"""\
Review the following pull request that was generated to fix a production bug.

## Bug Context
{crash_summary}

## Pull Request Diff
```diff
{pr_diff}
```

## Output Format
Return a JSON object with exactly these fields:

  test_coverage    — string description of whether the test covers the failure
                     path, e.g. "87% — new test directly exercises the crash path"
  standards_check  — "passed" or "failed"
  security_check   — "passed" or "failed"
  notes            — plain-English observations for the human reviewer (2–4 sentences)
  verdict          — "passed" or "failed" (overall; fail if any check fails)
  feedback         — if verdict is "failed": specific, actionable instructions
                     for the Dev Agent to fix the issues on retry.
                     Empty string if verdict is "passed".

Example shape:
{{
  "test_coverage": "Test directly triggers the KeyError path — coverage looks good.",
  "standards_check": "passed",
  "security_check": "passed",
  "notes": "Minimal fix. The guard clause is correct and consistent with the rest of the file.",
  "verdict": "passed",
  "feedback": ""
}}
"""
